language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

before_script:
  - ./gradlew clean

script:
  - ./gradlew build
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=162f82d286fd5c9fda4c1a96ef9f9c7c21470d9c
